export const eventConstants = {
    GETEVENT_REQUESTED: 'EVENT_REQUESTED',
    GETEVENT_SUCCESS: 'EVENT_SUCCESS',
    GETEVENT_FAILURE: 'EVENT_FAILURE',

    GETTEAMS_REQUESTED: 'EVENT_TEAMS_REQUESTED',
    GETTEAMS_SUCCESS: 'EVENT_TEAMS_SUCCESS',
    GETTEAMS_FAILURE: 'EVENT_TEAMS_FAILURE',

    GETRANKING_REQUESTED: 'EVENT_RANKING_REQUESTED',
    GETRANKING_SUCCESS: 'EVENT_RANKING_SUCCESS',
    GETRANKING_FAILURE: 'EVENT_RANKING_FAILURE',

    SETFIELDS_REQUESTED: 'EVT_FIELD_SET_REQUESTED',
    SETFIELDS_SUCCESS: 'EVT_FIELD_SET_SUCCESS',
    SETFIELDS_FAILURE: 'EVT_FIELD_SET_FAILURE',
};
