export const eventConstants = {
    GETEVENT_REQUESTED: 'EVENT_REQUESTED',
    GETEVENT_SUCCESS: 'EVENT_SUCCESS',
    GETEVENT_FAILURE: 'EVENT_FAILURE',

    GETTEAMS_REQUESTED: 'EVENT_TEAMS_REQUESTED',
    GETTEAMS_SUCCESS: 'EVENT_TEAMS_SUCCESS',
    GETTEAMS_FAILURE: 'EVENT_TEAMS_FAILURE',

    GET_SCORES_REQUESTED: 'EVENT_SCORES_REQUESTED',
    GET_SCORES_SUCCESS: 'EVENT_SCORES_SUCCESS',
    GET_SCORES_FAILURE: 'EVENT_SCORES_FAILURE',

    SETFIELDS_REQUESTED: 'EVT_FIELD_SET_REQUESTED',
    SETFIELDS_SUCCESS: 'EVT_FIELD_SET_SUCCESS',
    SETFIELDS_FAILURE: 'EVT_FIELD_SET_FAILURE',

    POST_RGSCORE_REQUESTED: 'EVT_POST_RGSCORE',
    POST_RGSCORE_SUCCESS: 'EVT_POST_RGSCORE_SUCCESS',
    POST_RGSCORE_FAILURE: 'EVT_POST_RGSCORE_FAILURE',

    POST_JGSCORE_REQUESTED: 'EVT_POST_JGSCORE',
    POST_JGSCORE_SUCCESS: 'EVT_POST_JGSCORE_SUCCESS',
    POST_JGSCORE_FAILURE: 'EVT_POST_JGSCORE_FAILURE',
};
