export const eventConstants = {
    GETBYID_REQUEST: 'EVENT_REQUEST',
    GETBYID_SUCCESS: 'EVENT_SUCCESS',
    GETBYID_FAILURE: 'EVENT_FAILURE',

    GETTEAMS_REQUEST: 'EVENT_TEAMS_REQUEST',
    GETTEAMS_SUCCESS: 'EVENT_TEAMS_SUCCESS',
    GETTEAMS_FAILURE: 'EVENT_TEAMS_FAILURE',
};
