export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

    DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    DELETE_FAILURE: 'USERS_DELETE_FAILURE',

    GETBYID_REQUEST: 'USERS_PROFILE_REQUEST',
    GETBYID_SUCCESS: 'USERS_PROFILE_SUCCESS',
    GETBYID_FAILURE: 'USERS_PROFILE_FAILURE',

    GET_EVTSMGR_REQUEST: 'USERS_PROFILE_EVTMGR_REQ',
    GET_EVTSJUDGE_REQUEST: 'USERS_PROFILE_EVTJUDGE_REQ',
    GET_EVTSREFR_REQUEST: 'USERS_PROFILE_EVTREFR_REQ',

    GET_EVTSMGR_SUCCESS: 'USERS_PROFILE_EVTMGR_SUCC',
    GET_EVTSJUDGE_SUCCESS: 'USERS_PROFILE_EVTJUDGE_SUCC',
    GET_EVTSREFR_SUCCESS: 'USERS_PROFILE_EVTREFR_SUCC',

    GET_EVTSMGR_FAILURE: 'USERS_PROFILE_EVTMGR_FAIL',
    GET_EVTSJUDGE_FAILURE: 'USERS_PROFILE_EVTJUDGE_FAIL',
    GET_EVTSREFR_FAILURE: 'USERS_PROFILE_EVTREFR_FAIL',

    GET_EVT_ROLES: 'USERS_GET_EVENT_ROLES',
    CLEAR_EVT_ROLES: 'USERS_CLEAR_EVENT_ROLES',
};
